#!/bin/bash
#
# File: setup
# Description: setup environment
# Author: Ronald Kaiser <raios DOT catodicos AT gmail DOT com>
#

DOTFILES="$HOME/bin/dotfiles"

task() {
    echo -e "\e[1;33m[$1]\e[0m"
}

task_done() {
    echo -e "\e[1;32mDone!\e[0m"
}

set_link() {
    local SRC="$1"
    local TGT="$2"

    if [ -s "$SRC" ]; then
        echo -e "\e[0;34m $SRC already exists. \e[0m"
        return 1
    fi
    ln -s $TGT $SRC && echo -e "\e[0;32m $SRC configured! \e[0m"
}

set_ssh() {
    task ssh
    set_link "$HOME/.ssh/config" "$DOTFILES/ssh/config" && task_done
}

set_vim() {
    task vim
    set_link "$HOME/.vimrc" "$DOTFILES/vim/vimrc" && task_done
}

set_git() {
    task git
    set_link "$HOME/.gitconfig" "$DOTFILES/git/gitconfig" && task_done
}

add_line() {
    local LINE="$1"
    local FILE="$2"
        
    if [ ! -f "$FILE" ]; then
        echo -e "\e[0;34mFile: $FILE does not exist. \e[0m"
        return 1        
    fi
    grep "$LINE" "$FILE"
    if [ ! "$?" = 0 ]; then
        echo "$LINE" >> "$FILE"
        if [ "$?" = 0 ]; then
            echo -e "\e[0;32mLine: \"$LINE\" added to $FILE!\e[0m"
        else
            return 1
        fi
    else
        echo -e "\e[0;34mLine: \"$LINE\" already exists in $FILE. \e[0m"
    fi
}
    
set_bashmarks() {
    task bashmarks
    git clone git://github.com/huyng/bashmarks.git /tmp/bashmarks
    if [ ! "$?" = 0 ]; then
        echo -e "\e[1;31mProblem during repository cloning.\e[0m"
        return 1
    fi

    cd /tmp/bashmarks && 
        make install >/dev/null &&
        add_line ". ~/.local/bin/bashmarks.sh" "$DOTFILES/bashrc" &&
        cd - &&
        rm -rf /tmp/bashmarks && 
        task_done
}

set_bashrc() {
    task bashrc
    touch ~/.bashrc && 
        add_line ". $DOTFILES/bashrc" ~/.bashrc &&
        task_done
}

set_perlbrew() {
    task perlbrew
    curl -kLO http://xrl.us/perlbrew && 
    perl perlbrew self-install &&
    $HOME/perl5/perlbrew/bin/perlbrew init && 
    add_line ". $HOME/perl5/perlbrew/etc/bashrc" "$DOTFILES/bashrc" &&
    rm perlbrew &&
    task_done
}

install_packages() {
    task packages
    uname -v | grep Ubuntu
    if [ "$?" = 0 ]; then
        sudo apt-get install $(cat .packages.debian) &&
        task_done && 
        return 0
    fi
    echo -e "\e[1;31mDon't know this OS\e[0m"
}

print_help() {
    echo "Usage: $(basename $0) [OPTIONS]

OPTIONS:
    -a, --all
    -r, --bashrc
    -v, --vim
    -s, --ssh
    -g, --git
    -k, --bashmarks
    -b, --perlbrew
    -p, --packages
    -h, --help"
}

while [ -n "$1" ]
do
    case $1 in
        -r | --bashrc) set_bashrc ;;
        -s | --ssh) set_ssh ;;
        -v | --vim) set_vim ;;
        -g | --git) set_git ;;
        -k | --bashmarks) set_bashmarks ;;
        -b | --perlbrew) set_perlbrew ;;
        -p | --packages) install_packages ;;
        -a | --all)
            set_bashrc
            set_ssh
            set_vim
            set_git
            set_bashmarks
            set_perlbrew
            install_packages
            ;;
        -h | --help) print_help;;
        *) echo "Invalid option: $1" && print_help
    esac
    shift
done
