"tab auto-completion for file paths
set wildmode=list:longest

set smartindent

"number lines
set nu

"number of spaces for a tab
set softtabstop=4

set shiftwidth=4

"replace \t per ' '
set expandtab

"searchs becomes highlighted
set hlsearch

"enables whitespace chars
"set list

"mouse interactions
set mouse=a

"break lines when reach width
"set tw=80

"highlight while typing
set incsearch

"colorscheme 
"colorscheme evening
"colorscheme ron 

"history size
set history=1000


"SHORTCUTS------------------
"remove trailing spaces
map <F3> <Esc>:%s/\s\+$//<CR>


"PLUGINS SESSION-------------

call pathogen#infect()
call pathogen#helptags()

"autoload NERDTree
au VimEnter *  NERDTree

"fuzzy finder
map ,f :FufFile<CR>

