#!/bin/bash

alias gt="git status"
alias h="history"
alias ..="cd .."
alias v="vim"

# command counter
function cc() {
    history | 
      awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | 
      sort -rn | 
      head
}
